# Generated by Django 5.0.6 on 2024-07-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['due_date']},
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='due',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='urgent',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
