# Generated by Django 5.0.6 on 2024-07-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todoitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['due']},
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='due_date',
            new_name='due',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
