# Generated by Django 5.0.6 on 2024-07-10 16:44

import markdownfield.models
import markdownfield.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todoitem_options_rename_due_date_todoitem_due_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', markdownfield.models.MarkdownField(rendered_field='rendered_text', validators=[markdownfield.validators.Validator])),
                ('rendered_text', markdownfield.models.RenderedMarkdownField()),
            ],
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(null=True, unique=False)
        ),
    ]
