# Generated by Django 5.0.6 on 2024-07-24 11:34

import markdownfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_editor_alter_todoitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('content', markdownfield.models.MarkdownField()),
                ('is_pinned', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
